data:
  local_path: "data"
  img_dir: "Images"
  annot_dir: "Annotation"
  img_db_uri: "img_db.csv"
  train_dir: "train"
  test_dir: "test"
  checkpoint_dir : "model_chkpts"

log:
  log_dir: "logs"